project:
  type: website
  output-dir: docs

website:
  title: "Intencionalidade, Vontade, Impulsividade e Livre Arbítrio"
  site-url: "https://henriquealvarenga.com"
  site-path: "/intencionalidade"
  favicon: favicon.ico
  
  navbar:
    background: primary
    left:
      - text: "Início"
        href: 1.0-index.qmd
      - text: "Casos Clínicos"
        href: 5.0-casos_clinicos.qmd
      - text: "Apêndices"
        href: 10.0-apendices.qmd          

    
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Início"
        contents:
          - text: "Prefácio"
            href: 00-prefacio.qmd  
          - text: "Introdução"
            href: 1.0-index.qmd             
          - text: "Da liberdade à Coordenação"
            href: 1.1-liberdade-coordenação.qmd
          - text: "Vontade"
            href: 1.2-vontade.qmd    
          - text: "De Tomás de Aquino a Davidson"
            href: 1.3-davidson.qmd                     
          - text: "Intencionalidade"
            href: 1.4-intencionalidade-pratica.qmd                     
          - text: "Impulsividade"
            href: 1.5-impulsividade.qmd
          - text: "Graus de Liberdade"          
            href: 1.6-graus-de-liberdade.qmd
          - text: "Neuroquimica"          
            href: 1.7-neuroquimica.qmd            
          - text: "Conclusão"
            href: 1.8-conclusao.qmd
      - section: "Casos"
        contents:
          - text: "Casos"
            href: 5.0-casos_clinicos.qmd        
          - text: "Lobotmia"
            href: 5.1-lobotomia.qmd
          - text: "Agressividade"
            href: 5.2-agressividade.qmd
          - text: "Pedofilia"
            href: 5.3-pedofilia.qmd    
          - text: "Hipersexualidade"
            href: 5.4-hipersexualidade.qmd       
          - text: "Cleptomania"
            href: 5.5-cleptomania.qmd 
          - text: "TOC"
            href: 5.6-toc.qmd   
          - text: "Tricotilomania"
            href: 5.7-tricotilomania.qmd                 
      - section: "Apêndices"
        contents:
          - text: "Sistemas Dinâmicos"
            href: 10.1-sistemas-dinamicos.qmd          
          - text: "Vontade nas Tradições Religiosas"
            href: 10.2-apendice-vontade-religioes.qmd
          - text: "Glossário"
            href: 10.3-glossario.qmd

  page-footer:
    left: "© 2025 Henrique Alvarenga"
    right: 
      - icon: github
        href: https://henriquealvarenga.com/intencionalidade

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: right
    number-sections: false
    code-fold: true
    code-tools: true
    smooth-scroll: true
    link-external-newwindow: true
    mermaid:
      theme: neutral
    
execute:
  freeze: auto
  echo: false
  warning: false
  message: false